# Generated by Django 3.1.7 on 2021-02-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210226_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='Name',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labreport',
            name='Phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
